version: 2
jobs:
  build:
    docker:
      - image: jmgao/ubuntu-cosmic-mingw-w64-rust:latest
    steps:
      - checkout
      - run:
          name: Pull submodules
          command: git submodule update --init
      - run:
          name: Install pkg-config
          command: apt-get install pkg-config
      - run:
          name: Install OpenSSL
          command: apt-get install libssl-dev
      - run:
          name: Build
          command: cargo build
      - run:
          name: Test
          command: cargo test
      - run:
          name: Clippy
          command: cargo clippy
