name: ci

on:
  push:

  pull_request:

  schedule:
    - cron: 00 4 * * *

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack,taplo-cli
      - run: taplo fmt --check --diff
        if: ${{ matrix.os != 'windows-latest' }} # https://github.com/tamasfe/taplo/issues/766
      - run: cargo fmt --all -- --check
      - run: cargo hack clippy --all-targets --feature-powerset --workspace -- --deny warnings
      - run: cargo hack test --all-targets --feature-powerset --workspace
